### ISSUE TITLE
clarify initial setup process?

### ISSUE THREAD

**Issue by tmuka** [uuf6429/httpdmon#33]
It seems i'm unable to use the updated httpdmon version. It's reporting "edmFATAL] No configuration loaded. (error 0, httpdmon:740) genericons.example.html.list.txt"

I tried to set it up fresh, but it's not clear to me how to make a config file.   I'm also not sure if I need a "definition file", and even what a definition file is.  it might be helpful to show an valid example value of $NAME in
"To download access/error log definitions, run the following command for the desired file (replace $NAME with the definition file name):"

Thanks!

**Comment by uuf6429** [comment]
Haven't worked on this since some time, for one thing it would be better to build a phar file instead of concatenating a bunch of classes into one big file.

Anyway, that aside, the definition file simply tells httpdmon where the log files are and how they should be parsed (some basic definitions can be [found here](https://github.com/uuf6429/httpdmon/tree/master/httpdmon.d)).

I'll try to write some clarifications later.

**Comment by tmuka** [comment]
Sorry, didn't realize it's been years!  

Thanks for the clarification, that makes sense. Thank you!
